In [8]:
import ISLP
import numpy as np

In [2]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [3]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [4]:
3+5

8

In [5]:
"hello" + " " + "world"

'hello world'

In [6]:
x = [3,4,5]
x

[3, 4, 5]

In [7]:
y = [4,9,7]
x+y

[3, 4, 5, 4, 9, 7]

Numpy

In [9]:
x = np.array([3,4,5])
y = np.array([4,9,7])

In [10]:
x+y

array([ 7, 13, 12])

In [12]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [13]:
x.ndim

2

In [14]:
x.dtype

dtype('int64')

In [15]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [16]:
np.array([[1,2],[3,4]], float).dtype

dtype('float64')

In [17]:
x.shape

(2, 2)

In [20]:
x = np.array([1,2,3,4])
x.sum()

10

In [21]:
np.sum(x)

10

In [23]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [30]:
x_reshape = x.reshape(3,2)
x_reshape

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
x_reshape[0,0]

1

In [32]:
x_reshape[1,1]

4

In [34]:
x[3]

4